### ISSUE TITLE
T1 reproducibility challenge data

### ISSUE THREAD

**Issue by siyuanhu1997** [rrsg2020/data_submission#1]
Hi! I am a participant of RRSG challenge. I am not sure what exact data files should I upload. Can I get a checklist that I can follow? Thank you!

**Comment by mathieuboudreau** [comment]
Hello! Thank you for registering! I just came back from paternity leave today - I will be adding you all to the email list this week and provide some general information. Expect these types of instructions (data format) to arrive later next week.

**Comment by siyuanhu1997** [comment]
Hi! I think I am ready for quality assurance review. Thank you!

**Comment by siyuanhu1997** [comment]
@mathieuboudreau Hi! I have collected all datasets, and wonder if they are what you want. Can I get some help on quality assurance review? Thanks!

**Comment by mathieuboudreau** [comment]
Hi @siyuanhu1997 ! Sorry for the delay, and thank you for your patience!

The submissions guidelines we have setup are on the README of this repo: https://github.com/rrsg2020/data_submission

Please have a look and don't hesitate to ask us any questions

**Comment by mathieuboudreau** [comment]
Great, thanks for submitting the data @siyuanhu1997 ! Because you opened your issue before we created the issue template, I'll copy the checklist in the next comment below.

**Comment by mathieuboudreau** [comment]
**Name**: Siyuan Hu

**Number of datasets (sets of inversion recovery measurements**: (INSERT NUMBER)

Submission Checklist:

* [ ] Have you collected all the raw data exported directly from scanner into a single folder?
* [ ] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [ ] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by mathieuboudreau** [comment]
Since you are the first submission, both @agahkarakuzu and I will review it/

**Comment by mathieuboudreau** [comment]
Hey @siyuanhu1997 !

One thing that was missed on our part in the *.yaml template is the serial number for your phantom (I'll be updating the template accordingly.). Would you mind sending it to us? It should be located on plate 5 according to this information: https://collaborate.nist.gov/mriphantoms/bin/view/MriPhantoms/PhantomOverview

Also, for the version, I think there are only two versions ("Phannie" and "Phreddie"). If you know which one yours is, that would be helpful as well. Otherwise, I think this information can be determined from your serial number.

Thanks!

**Comment by mathieuboudreau** [comment]
Actually, @agahkarakuzu  just corrected me. Phannie and Phreddie are the version names for the prototype production. If you purchased yours from HighPrecisionDevces/QualityMD, then it's likely version 130.

**Comment by siyuanhu1997** [comment]
Hi @mathieuboudreau, the serial number should be 0006.

**Comment by mathieuboudreau** [comment]
Hi @siyuanhu1997 

I had to do a few modifications to ensure that your submission matched our template (merged all inversion time files into a single NIFTI, with inversion times in the "time" dimension, modified the inversion_time config parameter to an array of values, and the data type config parameter (Magnitude)).

Your data was uploaded to the RRSG/qMRSG OSF.io repo: 

* NIST
  * https://osf.io/fa7p6/

* Human dataset
  * https://osf.io/x5df2/

I tested both of them in the demo processing pipeline, and they ran successfully.

# NIST

Pipeline output:

<img width="536" alt="Capture d’écran 2020-02-21 à 11 12 00" src="https://user-images.githubusercontent.com/1421029/75045642-3b057200-549e-11ea-803c-d325f9d02c57.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_01?filepath=data_submission%2Ft1_fitting_NIST.ipynb)

# Human

Pipeline output:

<img width="536" alt="Capture d’écran 2020-02-21 à 11 16 07" src="https://user-images.githubusercontent.com/1421029/75045652-4062bc80-549e-11ea-9c42-c2980e37ccbd.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_01?filepath=data_submission%2Ft1_fitting_human.ipynb)

Thank you for your submission!

**Comment by mathieuboudreau** [comment]
Hey @siyuanhu1997  - just a quick question.

I've never handled the phantom personally so I'm not sure if this is possible, but I was wondering if there's a possibility that the wrong plate was measured in your dataset. One of reasons why I ask is because the plate you imaged doesn't seem to contain the same "rectangle" in the center like for other phantom submissions I've seen (see #6. Also, our demo). The only other possibility I can think of is that because you have an early version of the phantom (< serial number 0042), that the manufacturer might not have included that rectangle in the T1 plate. The other phantoms that I've seen have been serial number >=0042.

Thanks!

**Comment by siyuanhu1997** [comment]
Hi @mathieuboudreau , the serial number of our phantom is 0006, which should be an early version.

**Comment by mathieuboudreau** [comment]
Oh yes I got that, I was just wondering if there's any chance that you mistakenly imaged the T2 or PD plates, instead of the T1. Maybe it's clearly indicated and would not be possible, I just wanted to ask and make sure.

**Comment by mathieuboudreau** [comment]
#9 is another submission that has that rectangle in the middle of the T1 plate that I was mentionning.

**Comment by siyuanhu1997** [comment]
I am pretty sure the measurement is on T1 layer, and there is no such rectangle in the layers of our NIST phantom

**Comment by mathieuboudreau** [comment]
Ok great - thanks a lot!
