### ISSUE TITLE
MREL at University of Southern California

### ISSUE THREAD

**Issue by namgyunlee** [rrsg2020/data_submission#18]
**Name**: MREL at University of Southern California (https://mrel.usc.edu/)

**Number of datasets (sets of inversion recovery measurements): 
6 phantom datasets acquired at two different days, two different GE scanners, and two different TRs.
1. Day 1, MR1, TR= 2500 msec
2. Day 1, MR2, TR= 2500 msec
3. Day 2, MR1, TR= 2500 msec
4. Day 2, MR1, TR=10000 msec
5. Day 2, MR2, TR= 2500  msec
6. Day 2, MR2, TR=10000 msec

Submission Checklist:

* [yes] Have you collected all the raw data exported directly from scanner into a single folder?
* [yes] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [yes] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by namgyunlee** [comment]
Dear Mathieu,

I have sent an email containing a link to each dataset. We are missing the serial number at this moment because the NIST phantom was borrowed from UCLA. We will contact them and find it out soon.

On behalf of the MREL at USC (Director: Krishna S. Nayak)
Yannick Bliesener
Ecem Bozkurt
Sreedevi Gutta
Kubra Keskin
Nam Lee
Bochao Li
Yongwan Lim
Erum Mushtaq
Ye Tian
Xitong Wang
Ziwei Zhao
Zhibo Zhu

**Comment by mathieuboudreau** [comment]
Hi @namgyunlee!

Thanks for submitting your dataset! Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/jwfep/

Do you know what's the serial number of the phantom you used? The reason why this information is needed is because the T1 values of serial numbers above or equal to 0042 are different from those for serial numbers below 0042 for your phantom version (130).

I fit two of your datasets with the demo scripts and it processed fine

#  Day 2 - MRI1 - TR = 2550 ms

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-06 à 21 28 56" src="https://user-images.githubusercontent.com/1421029/76133516-13142380-5ff3-11ea-8349-6a1b6cedf41f.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_18?filepath=data_submission%2Ft1_fitting_TR2550ms.ipynb)

#  Day 2 - MRI1 - TR = 10 000 ms

Pipeline output:

<img width="524" alt="Capture d’écran 2020-03-06 à 21 29 07" src="https://user-images.githubusercontent.com/1421029/76133518-17d8d780-5ff3-11ea-940e-53c5bb024571.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_18?filepath=data_submission%2Ft1_fitting_TR10000ms.ipynb)

The only thing missing from your submission to be complete is the serial number of your phantom, for the reason described above.

# To do

* [x] Provide serial number of NIST phantom

**Comment by mathieuboudreau** [comment]
Hey @namgyunlee !

Thanks for emailing an additional human dataset (6 subjects).

I've uploaded them to OSF.io here: https://osf.io/yu872/

I tried the demo pipeline on one of your subjects and it fit fine:

#  Human dataset (subject01)

Pipeline output:

<img width="526" alt="Capture d’écran 2020-03-08 à 21 48 24" src="https://user-images.githubusercontent.com/1421029/76173977-29eb7f00-6187-11ea-801e-872ed67674da.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_18?filepath=data_submission%2Ft1_fitting_human.ipynb)

**Comment by mathieuboudreau** [comment]
The NIST dataset hosted on osf.io has been updated with the serial numbers in the configuration file. Thanks @namgyunlee !
