### ISSUE TITLE
MD Anderson Cancer Center

### ISSUE THREAD

**Issue by cwmdanderson** [rrsg2020/data_submission#25]
**Name**: (INSERT_NAME)

**Number of datasets (sets of inversion recovery measurements**: (INSERT NUMBER)

Submission Checklist:

* [x] Have you collected all the raw data exported directly from scanner into a single folder?
* [x] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [x] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by cwmdanderson** [comment]
Our data is ready for quality assurance review

**Comment by mathieuboudreau** [comment]
Hi @cwmdanderson !

Thanks for submitting your dataset! 

While reviewing your dataset, there was two minor things I noticed that would greatly help if they could be shared. I understand that the pandemic has cause some lab accessibility issues, so these won't stop, but we would greatly appreciate it if you could provide these to us if you do have them

1- Phantom serial number. The reason why we need this is because the T1 values of the spheres actually changed for serial numbers after 0042, according to the documentation of the manufacturer. From your values, I'm suspecting that it is a phantom with a serial number > 0042, but knowing the exact number would be helpful.

2- The raw data that was exported from the scanner (e.g. DICOM). The reason why this is helpful is because there is a lot of header information lost when converting to NIFTI, so having the raw DICOMs can help us discover more about some potential sources of error in your measurements. 

Nonetheless, your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/praxv/

I tested your data with the demo fitting pipeline, at it fit correctly.

#  Day 1 NIST
Pipeline output:

<img width="521" alt="Capture d’écran 2020-04-10 à 18 01 17" src="https://user-images.githubusercontent.com/1421029/79089275-25832a80-7d20-11ea-840d-4ccdf393aac3.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_25?filepath=data_submission%2Ft1_fitting_day_1_NIST.ipynb)

I'll wait to hear back from you before closing this issue.

Thanks!

Mathieu

**Comment by cwmdanderson** [comment]
Hi Mathieu,

I don't remember the exact phantom serial number, but we did verify at the time of scan that it is after 0042 knowing the T1 change. I will go look it up.

I have added the raw dicoms to the shared Box folder. Please let me know if you have any issues accessing it.

Best,

Chenyang

**Comment by mathieuboudreau** [comment]
Great, thanks @cwmdanderson ! I've updated the OSF dataset with the raw data and that information. I'll close this issue now, but keep an "incomplete" tag as a reminder for the serial number so that we can add it later on.

Best regards,

Mathieu
