### ISSUE TITLE
UniPD

### ISSUE THREAD

**Issue by marcocastellaro** [rrsg2020/data_submission#7]
**Name**: Castellaro Marco

**Number of datasets (sets of inversion recovery measurements)**: 1

Submission Checklist:

* [X] Have you collected all the raw data exported directly from scanner into a single folder?
* [X] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [X] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

Data are ready for review.

**Comment by agahkarakuzu** [comment]
Hi @marcocastellaro, thank you for the submission! 

Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/n47jz/

I tested it in the processing pipeline, and it ran successfully.

Pipeline output:
![image](https://user-images.githubusercontent.com/9632322/75067220-8ded2280-54ba-11ea-9869-3f2f7ffbe7a7.png)

You can run it here: 

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_07?filepath=data_submission%2Ft1_fitting.ipynb)

**Comment by mathieuboudreau** [comment]
Hello @marcocastellaro  ,

As you are the designated person listed for your dataset, the challenge organizers sent you an email (email listed in your submission (marco.castellaro(AT)gmail.com) last July (subject: "2020 ISMRM T1 mapping challenge data consent"), but did not receive a response. Do you have an new email that we could resend it to, otherwise could you please check if the original email was received? Thank you.
