### ISSUE TITLE
UTHealth

### ISSUE THREAD

**Issue by rgabr** [rrsg2020/data_submission#8]
**Name**: (Refaat Gabr)

**Number of datasets (sets of inversion recovery measurements**: (1)

Submission Checklist:

* [X] Have you collected all the raw data exported directly from scanner into a single folder?
* [X] For each dataset, did you create one (or two, if complex) NIFTI files with each inversion time measurement in the "time" dimension?
* [X] For each NIFTI file, did you create a YAML file with the same filename containing the necessary details about your dataset for the challenge? (See sample [submission on OSF.io](https://osf.io/9j3pa/) for a template)

When your data is ready for review, please comment in your issue and email a link to a Google Drive folder (or other online data sharing service) containing your data to: rrsg.challenge@gmail.com.

**Comment by rgabr** [comment]
Data ready; email sent with Google Drive link.

**Comment by mathieuboudreau** [comment]
Hi @rgabr ,

Thanks for your submission. I think that mistakenly, the phase images were converted to NIFTI instead of magnitude, as the NIFTI files you provided to me didn't appear right. Thankfully you included the raw DICOMS, so when I did the conversion to NIFTI myself, I was able to choose the magnitude data instead.

Your data was uploaded to the RRSG/qMRSG OSF.io repo: https://osf.io/b2sm8/

I tested it in the processing pipeline, and it ran successfully.

Pipeline output:

<img width="536" alt="Capture d’écran 2020-02-24 à 16 37 25" src="https://user-images.githubusercontent.com/1421029/75187227-381bb300-5724-11ea-9c5c-6aedd1f0ae4b.png">

Run it here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/rrsg2020/data_submission/issue_08?filepath=data_submission%2Ft1_fitting.ipynb)

**Comment by rgabr** [comment]
Thank you!

Refaat Gabr

**Comment by mathieuboudreau** [comment]
Hello @rgabr,

As you are the designated person listed for your dataset, the challenge organizers sent you an email (email listed in your submission (refaat.e.gabr(AT)uth.tmc.edu) last July (subject: "2020 ISMRM T1 mapping challenge data consent"), but did not receive a response. Do you have an new email that we could resend it to, otherwise could you please check if the original email was received? Thank you.

**Comment by rgabr** [comment]
Hi Mathieu,

Yes I am the person of contact and organizer for UTHealth participation. I
am sorry I missed your email earlier as I moved to another position outside
UTHealth (but still associated with UTHealth). I will look into the
previous email ASAP and act accordingly. Apologies again.

Best,
Refaat

Refaat Gabr, PhD
Principal Scientist, Biogen
Adjunct Associate Professor, UTHealth
